#!/usr/bin/env python3
"""
Export Service for transcripts
Supports TXT, JSON, and PDF formats
"""

import json
import os
from datetime import datetime
from typing import Dict, List, Optional
from pathlib import Path
import logging

logger = logging.getLogger(__name__)

class ExportService:
    """Handle transcript exports in various formats"""
    
    def __init__(self):
        self.export_dir = Path("/tmp/exports")
        self.export_dir.mkdir(exist_ok=True)
    
    def export_txt(self, session_data: Dict, include_timestamps: bool = True, 
                   include_speakers: bool = True) -> str:
        """Export transcript as plain text"""
        output = []
        
        # Header
        output.append("=" * 80)
        output.append(f"Meeting Transcript - {session_data.get('session_id', 'Unknown')}")
        output.append(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        if 'duration' in session_data:
            output.append(f"Duration: {self._format_duration(session_data['duration'])}")
        output.append("=" * 80)
        output.append("")
        
        # Summary if available
        if 'summary' in session_data:
            output.append("SUMMARY")
            output.append("-" * 40)
            output.append(session_data['summary'])
            output.append("")
        
        # Transcript
        output.append("TRANSCRIPT")
        output.append("-" * 40)
        
        if 'segments' in session_data:
            # Structured transcript with segments
            for segment in session_data['segments']:
                line = ""
                
                if include_timestamps and 'start_time' in segment:
                    line += f"[{self._format_time(segment['start_time'])}] "
                
                if include_speakers and 'speaker' in segment:
                    line += f"{segment['speaker']}: "
                
                line += segment.get('text', '')
                output.append(line)
        else:
            # Simple text transcript
            output.append(session_data.get('transcript', session_data.get('text', '')))
        
        output.append("")
        output.append("=" * 80)
        output.append("Generated by Unicorn Commander Meeting Ops")
        
        return "\n".join(output)
    
    def export_json(self, session_data: Dict, pretty: bool = True) -> str:
        """Export transcript as JSON"""
        export_data = {
            "metadata": {
                "session_id": session_data.get('session_id'),
                "export_date": datetime.now().isoformat(),
                "duration": session_data.get('duration'),
                "audio_file": session_data.get('audio_file'),
                "model": session_data.get('model', 'whisper-base'),
                "npu_accelerated": session_data.get('npu_accelerated', False)
            },
            "summary": session_data.get('summary', ''),
            "transcript": {
                "text": session_data.get('transcript', session_data.get('text', '')),
                "segments": session_data.get('segments', []),
                "speakers": session_data.get('speakers', [])
            },
            "performance": session_data.get('performance', {})
        }
        
        if pretty:
            return json.dumps(export_data, indent=2, ensure_ascii=False)
        else:
            return json.dumps(export_data, ensure_ascii=False)
    
    def export_pdf(self, session_data: Dict) -> bytes:
        """Export transcript as PDF"""
        try:
            from reportlab.lib.pagesizes import letter, A4
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import inch
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
            from reportlab.platypus import Table, TableStyle
            from reportlab.lib import colors
            from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
            
            # Create PDF file in memory
            from io import BytesIO
            buffer = BytesIO()
            
            # Create document
            doc = SimpleDocTemplate(
                buffer,
                pagesize=letter,
                rightMargin=72,
                leftMargin=72,
                topMargin=72,
                bottomMargin=18,
            )
            
            # Container for elements
            elements = []
            styles = getSampleStyleSheet()
            
            # Custom styles
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=24,
                textColor=colors.HexColor('#1f2937'),
                spaceAfter=30,
                alignment=TA_CENTER
            )
            
            heading_style = ParagraphStyle(
                'CustomHeading',
                parent=styles['Heading2'],
                fontSize=16,
                textColor=colors.HexColor('#374151'),
                spaceAfter=12,
                spaceBefore=12
            )
            
            # Title
            elements.append(Paragraph("Meeting Transcript", title_style))
            elements.append(Spacer(1, 0.2 * inch))
            
            # Metadata table
            metadata = [
                ['Session ID:', session_data.get('session_id', 'N/A')],
                ['Date:', datetime.now().strftime('%Y-%m-%d %H:%M:%S')],
                ['Duration:', self._format_duration(session_data.get('duration', 0))],
                ['Model:', session_data.get('model', 'whisper-base')],
                ['NPU Accelerated:', 'Yes' if session_data.get('npu_accelerated') else 'No']
            ]
            
            t = Table(metadata, colWidths=[2*inch, 4*inch])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.grey),
                ('TEXTCOLOR', (0, 0), (0, -1), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            elements.append(t)
            elements.append(Spacer(1, 0.5 * inch))
            
            # Summary section
            if session_data.get('summary'):
                elements.append(Paragraph("Summary", heading_style))
                summary_style = ParagraphStyle(
                    'Summary',
                    parent=styles['Normal'],
                    fontSize=11,
                    textColor=colors.HexColor('#4b5563'),
                    alignment=TA_JUSTIFY,
                    spaceAfter=12
                )
                elements.append(Paragraph(session_data['summary'], summary_style))
                elements.append(Spacer(1, 0.3 * inch))
            
            # Transcript section
            elements.append(Paragraph("Transcript", heading_style))
            
            transcript_style = ParagraphStyle(
                'Transcript',
                parent=styles['Normal'],
                fontSize=10,
                leading=14,
                textColor=colors.HexColor('#374151')
            )
            
            if 'segments' in session_data:
                for segment in session_data['segments']:
                    text = ""
                    if 'start_time' in segment:
                        text += f"<b>[{self._format_time(segment['start_time'])}]</b> "
                    if 'speaker' in segment:
                        text += f"<b>{segment['speaker']}:</b> "
                    text += segment.get('text', '')
                    
                    elements.append(Paragraph(text, transcript_style))
                    elements.append(Spacer(1, 0.1 * inch))
            else:
                text = session_data.get('transcript', session_data.get('text', ''))
                elements.append(Paragraph(text, transcript_style))
            
            # Footer
            elements.append(Spacer(1, 0.5 * inch))
            footer_style = ParagraphStyle(
                'Footer',
                parent=styles['Normal'],
                fontSize=8,
                textColor=colors.grey,
                alignment=TA_CENTER
            )
            elements.append(Paragraph("Generated by Unicorn Commander Meeting Ops", footer_style))
            
            # Build PDF
            doc.build(elements)
            
            # Return PDF bytes
            buffer.seek(0)
            return buffer.read()
            
        except ImportError:
            logger.error("ReportLab not installed. Install with: pip install reportlab")
            raise RuntimeError("PDF export requires ReportLab: pip install reportlab")
    
    def _format_duration(self, seconds: float) -> str:
        """Format duration in seconds to human readable"""
        if not seconds:
            return "0:00"
        
        hours = int(seconds // 3600)
        minutes = int((seconds % 3600) // 60)
        secs = int(seconds % 60)
        
        if hours > 0:
            return f"{hours}:{minutes:02d}:{secs:02d}"
        else:
            return f"{minutes}:{secs:02d}"
    
    def _format_time(self, seconds: float) -> str:
        """Format timestamp"""
        return self._format_duration(seconds)
    
    def save_export(self, session_id: str, format: str, content: any) -> str:
        """Save export to file and return path"""
        filename = f"{session_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.{format}"
        filepath = self.export_dir / filename
        
        if format == 'pdf':
            with open(filepath, 'wb') as f:
                f.write(content)
        else:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)
        
        logger.info(f"✅ Exported {format.upper()} to: {filepath}")
        return str(filepath)


# Example usage
if __name__ == "__main__":
    # Test export service
    service = ExportService()
    
    # Sample data
    test_data = {
        "session_id": "test_123",
        "duration": 185.5,
        "transcript": "This is a test transcript.",
        "summary": "Key points discussed in the meeting.",
        "segments": [
            {
                "start_time": 0.0,
                "speaker": "Speaker 1",
                "text": "Hello everyone, let's begin the meeting."
            },
            {
                "start_time": 5.2,
                "speaker": "Speaker 2", 
                "text": "Thank you for joining. Today we'll discuss the project status."
            }
        ],
        "npu_accelerated": True,
        "model": "whisper-base"
    }
    
    # Test TXT export
    txt_content = service.export_txt(test_data)
    print("TXT Export:\n", txt_content[:200], "...\n")
    
    # Test JSON export
    json_content = service.export_json(test_data)
    print("JSON Export:\n", json_content[:200], "...\n")
    
    # Test PDF export (if ReportLab is installed)
    try:
        pdf_content = service.export_pdf(test_data)
        print(f"PDF Export: Generated {len(pdf_content)} bytes")
    except Exception as e:
        print(f"PDF Export failed: {e}")