[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
prompt = no

[req_distinguished_name]
C = US
ST = California
L = Silicon Valley
O = Magic Unicorn Inc
OU = Meeting-Ops Division
CN = meeting-ops.local
emailAddress = admin@magicunicorn.tech

[v3_req]
keyUsage = keyEncipherment, dataEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = localhost
DNS.2 = meeting-ops.local
DNS.3 = *.meeting-ops.local
DNS.4 = meetingops.local
DNS.5 = uc-1.local
IP.1 = 127.0.0.1
IP.2 = ::1
IP.3 = 192.168.1.145
IP.4 = 192.168.1.223
IP.5 = 192.168.0.1
IP.6 = 10.0.0.1
IP.7 = 172.16.0.1
